### ISSUE TITLE
Subscriber import httpstatus 500

### ISSUE THREAD

**Issue by mattgenious** [campaignmonitor/createsend-dotnet#63]
I am experiencing an error where the bulk import throws an exceptions without any ErrorResult data and the task seems to have failed completely.

It throws the following exception
```
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at createsend_dotnet.HttpHelper.MakeRequest[T,U,EX](String method, AuthenticationDetails auth, String path, NameValueCollection queryArguments, T payload, String baseUri, String contentType)
   at createsend_dotnet.HttpHelper.Post[T,U,EX](AuthenticationDetails auth, String path, NameValueCollection queryArguments, T payload, String baseUri, String contentType)
   at createsend_dotnet.CreateSendBase.HttpPost[T,U,EX](String path, NameValueCollection queryArguments, T payload)
   at createsend_dotnet.Subscriber.Import(List`1 subscribers, Boolean resubscribe, Boolean queueSubscriptionBasedAutoResponders, Boolean restartSubscriptionBasedAutoresponders)
```
Until recently it would throw an exception with error results in the data property of the exception that I could use.
Let me know if you need more information to solve the issue.

**Comment by edgunn** [comment]
@mattgenious Thanks for bringing this up, we've just released a fix. Do you mind confirming that the issue is resolved?

**Comment by mattgenious** [comment]
Everything seems to be working fine now thanks @edgunn .
